# render.yaml
services:
  - type: web
    name: gemini-ai-backend
    env: node
    buildCommand: npm install # This will run the root package.json install
    startCommand: npm start # This will run the root package.json start
    rootDir: ./
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production